---
- name: install software
  hosts: 127.0.0.1

  tasks:
  - name: Download chrome
    ansible.builtin.get_url:
      url: http://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/
  - name: Install chrome
    ansible.builtin.apt:
      deb: /tmp/google_chrome_stable_current_amd64.deb
    become: yes